# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: WeUseCoins Forum

# Short description (goes below the title; it will also be used in the RSS feed)
description: WeUseCoins forum for discussion on crypto-currency and blockchain technology.

# Your name, as you want it to appear underneath each post and in the footer
author: WeUseCoins

# Uncomment if you are planning to run the blog in a subdirectory
# Note - if you enable this, and attempt to view your site locally you have to use the baseurl in your local path.
# Example, you must use http://localhost:4000/path/to/blog
baseurl: /forum

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: https://www.weusecoins.com/forum

# Exclude system files
exclude: [.gitignore]

# The disqus shortname for your forum
disqus_shortname: weusecoins

# The public key for your disqus application
disqus_publickey: MfUcnIi9YQO2slHWW9c1jkMmu0FUb5CjE3bl5Dau4VMPEv4kDRJlH6kdrsbEOecA
